apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
  namespace: marvel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uaa
      version: 'v1'
  template:
    metadata:
      labels:
        app: uaa
        version: 'v1'
    spec:
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 uaa-mongodb 27017)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: uaa-app
          image: anantgowadiya/uaa
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://admin:${jhipster.registry.password}@jhipster-registry.marvel.svc.cluster.local:8761/config
            - name: JHIPSTER_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-secret
                  key: registry-admin-password
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://admin:${jhipster.registry.password}@jhipster-registry.marvel.svc.cluster.local:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: 'false'
            - name: EUREKA_INSTANCE_HOSTNAME
              value: uaa
            - name: SPRING_DATA_MONGODB_DATABASE
              value: uaa
            - name: SPRING_DATA_MONGODB_URI
              value: 'mongodb://uaa-mongodb-0.uaa-mongodb.marvel:27017,uaa-mongodb-1.uaa-mongodb.marvel:27017,uaa-mongodb-2.uaa-mongodb.marvel:27017'
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: 'x-request-id,x-ot-span-context'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 9999
          readinessProbe:
            httpGet:
              path: /management/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/info
              port: http
            initialDelaySeconds: 120
